version: "3"

services:
  # php-apache:
  #   build: .
  #   volumes:
  #     - .:/var/www/html
  #   ports:
  #     - 5001:80
  #   links:
  #     - db:db
  #   depends_on:
  #     - db
  db:
    image: custom-mysql
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shareboard
    # volumes:
    #   - ./db/data:/var/lib/mysql
